### ISSUE TITLE
Gsettings won't work with i3

### ISSUE THREAD

**Issue by Hachiverol** [anirudhajith/process-wallpaper#14]
I see the original version of the setWallpaper.sh file prioritized feh. But the repo version uses gsettings. Some apps install gsettings at their dependency. it gets detected but doesn't work.
Feh works with almost anything. Can it be reversed back in the repo so people don't get confused?

**Comment by anirudhajith** [comment]
`feh` is installed on my machine running GNOME but it doesn't change the wallpaper. I'm not sure why. Do you think it would be a good idea to try running both commands (if they are installed, that is)?

**Comment by Hachiverol** [comment]
I mean sure one of them is bound to change the wallpaper. I was planning to
add nitrogen support but it would seem like it doesn't cooperate via the
terminal. So script wise it's unusable. Yes running both commands would be
a better way to ensure the change.

**Comment by anirudhajith** [comment]
> Yes running both commands would be a better way to ensure the change.

I've committed changes implementing this.
