### ISSUE TITLE
KDE Plasma support.

### ISSUE THREAD

**Issue by dsluo** [anirudhajith/process-wallpaper#19]
Neither `feh` nor `gsettings` work on Plasma. Plasma uses a `dbus`-based system to manage its functions and doesn't provide a script to do this out of the box. [This reddit thread](https://www.reddit.com/r/kde/comments/65pmhj/change_wallpaper_from_terminal/dgc5qzy/) will probably be of some help when this is fixed.

**Comment by anirudhajith** [comment]
Resolved by #23.
