### ISSUE TITLE
Python script not working

### ISSUE THREAD

**Issue by ghost** [anirudhajith/process-wallpaper#3]
I would like to use your script, but when it's time to execute python program, an error appears.

`Traceback (most recent call last):
  File "generateWallpaper.py", line 20, in <module>
    cpu = float(fields[8])
ValueError: could not convert string to float: '25,0'
`

**Comment by Dafnik** [comment]
Fixed in #1.

**Comment by pessip** [comment]
I think this #1 fixes it.
