### ISSUE TITLE
Error in "generateWallpaper.py".

### ISSUE THREAD

**Issue by Phate6660** [anirudhajith/process-wallpaper#4]
```
Traceback (most recent call last):
  File "generateWallpaper.py", line 15, in <module>
    if fields[11].count("/") > 0:
IndexError: list index out of range
```

**Comment by Kodehawa** [comment]
I get the following error too:

```
20:00:44 › python generateWallpaper.py
Traceback (most recent call last):
  File "generateWallpaper.py", line 20, in <module>
    cpu = float(fields[8])
ValueError: could not convert string to float: '0,0'
```

**Comment by ndlrx** [comment]
> I get the following error too:
> 
> ```
> 20:00:44 › python generateWallpaper.py
> Traceback (most recent call last):
>   File "generateWallpaper.py", line 20, in <module>
>     cpu = float(fields[8])
> ValueError: could not convert string to float: '0,0'
> ```

I got an error as yours..
And resolved by adding this..
https://github.com/anirudhajith/process-wallpaper/pull/1/files

**Comment by Kodehawa** [comment]
tfw I opened my own and I totally didn't see there was another one.

**Comment by anirudhajith** [comment]
Thanks for you pull request. I presume this is no longer an issue.

**Comment by Phate6660** [comment]
@anirudhajith 

I believe their error was different from mine. I still get the error I said before.

```
Traceback (most recent call last):
  File "generateWallpaper.py", line 15, in <module>
    if fields[11].count("/") > 0:
IndexError: list index out of range
```

**Comment by anirudhajith** [comment]
I suspect that some bad output padding from `top.out` may be sneaking in. I've put in a try/except. Can you pull and see if it works now?

**Comment by Phate6660** [comment]
Sorry for the late response. I was sleeping.

Everything works perfectly now. Thank you.
